import logger from '../../../core/logger/logger.js';
import { ApiError } from '../../../core/errors/ApiError.js';
import { createOrder, verifyAndConfirmPayment, getOrderDetail } from '../services/paymentService.js';
import { validateQRPayment, closeRideQR } from '../../../core/services/qrService.js';
import * as rideService from '../../rides/services/rideService.js';

/**
 * Generate QR code for payment (Driver generates after ride completion)
 * @param {Object} req - Express request object
 * @param {Object} res - Express response object
 */
export const generatePaymentQR = async (req, res) => {
    try {
        const userId = req.user.id;
        const { ride_id } = req.body;

        // Validate required fields
        if (!ride_id) {
            throw new ApiError(400, 'Ride ID is required for QR payment generation');
        }

        // Get ride details to verify driver access and ride completion
        const ride = await rideService.getRideDetails(userId, ride_id, 'driver');
        if (!ride) {
            throw new ApiError(404, 'Ride not found or access denied');
        }

        // Check if ride is completed
        if (ride.status !== 'completed') {
            throw new ApiError(400, 'Ride must be completed before generating QR payment');
        }

        // Check if payment method is QR
        if (ride.paymentMethod !== 'qr') {
            throw new ApiError(400, 'QR payment can only be generated for rides with QR payment method');
        }

        // Check if QR payment already exists for this ride
        if (ride.paymentStatus === 'paid') {
            throw new ApiError(400, 'Payment already completed for this ride');
        }

        // Generate amount from ride fare
        const amount = ride.finalFare || ride.estimatedFare;

        if (amount <= 0) {
            throw new ApiError(400, 'Invalid ride amount');
        }

        // Create payment order with QR method for specific ride
        const result = await createOrder(userId, {
            amount,
            purpose: 'ride_payment',
            payment_method: 'qr',
            payment_gateway: 'razorpay',
            ride_id,
            description: `QR payment for ride ${ride.rideNumber}`,
            metadata: { 
                qr_payment: true,
                ride_number: ride.rideNumber,
                passenger_id: ride.passenger?.id,
                driver_id: ride.driver?.id
            }
        });

        logger.info(`[QR Payment] QR generated by driver | Driver: ${userId} | Ride: ${ride_id} | Order: ${result.data.order.orderNumber}`);

        res.status(201).json({
            success: true,
            message: 'QR code generated successfully for ride payment',
            data: {
                ...result.data,
                ride: {
                    id: ride.id,
                    rideNumber: ride.rideNumber,
                    amount: amount,
                    passenger: ride.passenger?.fullName || 'Passenger'
                }
            }
        });

    } catch (error) {
        logger.error('[QR Payment] Generate QR error:', error);
        res.status(error.statusCode || 500).json({
            success: false,
            message: error.message || 'Failed to generate QR code',
            data: {}
        });
    }
};

/**
 * Verify QR code payment (Passenger scans QR and pays)
 * @param {Object} req - Express request object
 * @param {Object} res - Express response object
 */
export const verifyQRPayment = async (req, res) => {
    try {
        const userId = req.user.id;
        const { order_number, gateway_payment_id, gateway_signature } = req.body;

        // Validate required fields
        if (!order_number || !gateway_payment_id || !gateway_signature) {
            throw new ApiError(400, 'Order number, payment ID, and signature are required');
        }

        // Get order details to verify passenger access
        const orderResponse = await getOrderDetail(userId, order_number);
        const order = orderResponse.data.order;

        // Check if this is a QR payment for a ride
        if (order.paymentMethod !== 'qr' || order.purpose !== 'ride_payment') {
            throw new ApiError(400, 'This is not a valid ride QR payment');
        }

        // Get ride details to verify passenger is the ride owner
        const ride = await rideService.getRideDetails(userId, order.rideId, 'passenger');
        if (!ride) {
            throw new ApiError(403, 'You are not authorized to pay for this ride');
        }

        // Validate QR payment
        const qrValidation = await validateQRPayment({
            orderNumber: order_number,
            gatewayPaymentId: gateway_payment_id,
            gatewaySignature: gateway_signature
        });

        if (!qrValidation.success) {
            throw new ApiError(400, 'QR payment validation failed');
        }

        // Verify and confirm payment with Razorpay
        const result = await verifyAndConfirmPayment({
            gateway_order_id: order_number,
            gateway_payment_id,
            gateway_signature
        });

        // Update ride payment status to paid
        await rideService.updateRidePaymentStatus(order.rideId, {
            payment_status: 'paid',
            payment_method: 'qr',
            payment_collected_at: new Date(),
            gateway_payment_id: gateway_payment_id,
            gateway_order_id: order_number
        });

        logger.info(`[QR Payment] QR payment completed | Passenger: ${userId} | Ride: ${order.rideId} | Order: ${order_number}`);

        res.status(200).json({
            success: true,
            message: 'QR payment completed successfully',
            data: {
                ...result.data,
                ride: {
                    id: ride.id,
                    rideNumber: ride.rideNumber,
                    amount: order.amount,
                    paymentStatus: 'paid',
                    paidAt: new Date()
                }
            }
        });

    } catch (error) {
        logger.error('[QR Payment] Verify QR error:', error);
        res.status(error.statusCode || 500).json({
            success: false,
            message: error.message || 'Failed to verify QR payment',
            data: {}
        });
    }
};

/**
 * Get QR payment status
 * @param {Object} req - Express request object
 * @param {Object} res - Express response object
 */
export const getQRPaymentStatus = async (req, res) => {
    try {
        const userId = req.user.id;
        const { order_number } = req.params;

        if (!order_number) {
            throw new ApiError(400, 'Order number is required');
        }

        // Get order details
        const orderResponse = await getOrderDetail(userId, order_number);
        const order = orderResponse.data.order;

        // Check if this was a QR payment
        if (order.paymentMethod !== 'qr') {
            throw new ApiError(400, 'This is not a QR payment order');
        }

        res.status(200).json({
            success: true,
            message: 'QR payment status retrieved',
            data: {
                order,
                qrStatus: order.status === 'success' ? 'completed' : 'pending',
                expiresAt: order.expiresAt
            }
        });

    } catch (error) {
        logger.error('[QR Payment] Get status error:', error);
        res.status(error.statusCode || 500).json({
            success: false,
            message: error.message || 'Failed to get QR payment status',
            data: {}
        });
    }
};

/**
 * Close QR payment (cancel/expire)
 * @param {Object} req - Express request object
 * @param {Object} res - Express response object
 */
export const closeQRPayment = async (req, res) => {
    try {
        const userId = req.user.id;
        const { order_number } = req.body;

        if (!order_number) {
            throw new ApiError(400, 'Order number is required');
        }

        // Get order details to find ride_id
        const orderResponse = await getOrderDetail(userId, order_number);
        const order = orderResponse.data.order;

        if (order.rideId) {
            // Close QR for ride payment
            await closeRideQR(order.rideId);
        }

        logger.info(`[QR Payment] QR closed | User: ${userId} | Order: ${order_number}`);

        res.status(200).json({
            success: true,
            message: 'QR payment closed successfully',
            data: {}
        });

    } catch (error) {
        logger.error('[QR Payment] Close QR error:', error);
        res.status(error.statusCode || 500).json({
            success: false,
            message: error.message || 'Failed to close QR payment',
            data: {}
        });
    }
};
